#!/bin/bash

set -e

CATALINA_HOME=/usr/share/tomcat9-codedeploy
TOMCAT_VERSION=9.0.8
#wget http://apache.mirrors.ionfish.org/tomcat/tomcat-9/v9.0.8/bin/apache-tomcat-9.0.8.tar.gz
# Tar file name
tomcat9_CORE_TAR_FILENAME="apache-tomcat-$TOMCAT_VERSION.tar.gz"
# Download URL for tomcat9 core
tomcat9_CORE_DOWNLOAD_URL="http://apache.mirrors.ionfish.org/tomcat/tomcat-9/v$TOMCAT_VERSION/bin/$tomcat9_CORE_TAR_FILENAME"
# The top-level directory after unpacking the tar file
tomcat9_CORE_UNPACKED_DIRNAME="apache-tomcat-$TOMCAT_VERSION"


# Check whether there exists a valid instance
# of tomcat9 installed at the specified directory
[[ -d $CATALINA_HOME ]] && { service tomcat9 status; } && {
    echo "tomcat9 is already installed at $CATALINA_HOME. Skip reinstalling it."
    exit 0
}

# Clear install directory
if [ -d $CATALINA_HOME ]; then
    rm -rf $CATALINA_HOME
fi
mkdir -p $CATALINA_HOME

# Download the latest tomcat9 version
cd /tmp
{ which wget; } || { yum install wget; }
wget $tomcat9_CORE_DOWNLOAD_URL
if [[ -d /tmp/$tomcat9_CORE_UNPACKED_DIRNAME ]]; then
    rm -rf /tmp/$tomcat9_CORE_UNPACKED_DIRNAME
fi
tar xzf $tomcat9_CORE_TAR_FILENAME

# Copy over to the CATALINA_HOME
cp -r /tmp/$tomcat9_CORE_UNPACKED_DIRNAME/* $CATALINA_HOME

# Install Java if not yet installed
{ which java; } || { yum install java; }

# Create the service init.d script
cat > /etc/init.d/tomcat9 <<'EOF'
#!/bin/bash
# description: tomcat9 Start Stop Restart
# processname: tomcat9
PATH=$JAVA_HOME/bin:$PATH
export PATH
CATALINA_HOME='/usr/share/tomcat9-codedeploy'

case $1 in
start)
sh $CATALINA_HOME/bin/startup.sh
;;
stop)
sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
sh $CATALINA_HOME/bin/shutdown.sh
sh $CATALINA_HOME/bin/startup.sh
;;
esac
exit 0
EOF

# Change permission mode for the service script
chmod 755 /etc/init.d/tomcat9

